config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  resources :items
  # devise_for :users
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord

  with_options presence: true do
    validates :title
    validates :price
    validates :content
    validates :images
  end
  
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :find_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all.order(created_at: :desc)
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to root_path, notice: "メニューが更新されました"
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    if @item.destroy
      redirect_to root_path, notice: "メニューが削除されました"
    else
      redirect_to root_path, notice: "メニューが削除されませんでした"
    end
  end

  private

  def item_params
    params.require(:item).permit(:title, :content, :price).merge(user_id: current_user.id)
  end

  def find_item
    @item = Item.find(params[:id])
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="item-form">
  <%= form_with model:@item, url: items_path, method: :post, local: true do |f| %>
    <div class="img-upload">
      <div class="click-upload">
          <p>クリックして画像ファイルをアップロード</p>
          <%= f.file_field :images, multiple: true, id:"item-image" %>
      </div>
    </div>

    <div class="new-items">
      <div class="weight-bold-text">
        メニュー名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :title, class:"items-text", id:"item-name", placeholder:"メニュー名(必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          メニューの説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :content, class:"items-text", id:"item-info", placeholder:"メニューの説明(必須 1,000文字まで)", maxlength:"1000" %>
      </div>
    </div>

    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(300~9,999,999円以内)</span>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例) 300" %>
        </div>
      </div>
    </div>

    <div class="sell-btn-contents">
      <%= f.submit "投稿する", class:"button" %>
      <%= link_to "戻る", root_path, class:"back-btn" %>
    </div>

  <% end %>
</div>

app/views/items/edit.html.erb
<div class="items-sell-main">
    <h1 class="items-sell-title">メニューの情報を更新</h1>
    <%= render 'form'%>    
</div>

app/views/items/index.html.erb
<div class="content-wrapper">
  <div class="content-block">
  <%# <% @items.each do |item| %>
    <div class="content">
          <div class="user-about">
            <div class="image">
              <%# <% if item.user.image.attached? %>
                <%# <%= image_tag item.user.image %>
              <%# <% else %>
                 <%= image_tag "nouser.png" %>
              <%# <% end %>
            </div>

            <div class="profile">
              <div class="name-about">
                <div class="name">
                和食割烹　熊谷
                  <%# <%= item.user.name %>
                </div>
              </div>
              <div class="detail">
              大正時代に創業
                <%# <%= item.user.detail %>
              </div>
            </div>
          </div>

          <%# <% if item.images.attached? %>
            <div class="images">
              <%# <%= link_to item_path(item.id) do %>
                <%# <% item.images.each do |image| %>
                <%# <%= image_tag image %>
              <%# <% end %>
            </div>
          <%# <% end %>
        <%# <% end %>


        <div class="text">
        <p>サンプルテキストですサンプルテキストですサンプルテキストですサンプルテキストです</p>
        <p>サンプルテキストですサンプルテキストですサンプルテキストですサンプルテキストです</p>
           <%# <%= item.content %>
        </div>
      </div>
   <%# <% end %>
  </div>
</div>

app/views/items/new.html.erb
<div class="items-sell-main">
  <h1 class="items-sell-title">メニューの情報を入力</h1>
  <%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="<%= controller.controller_name %>-<%= controller.action_name %>">
  <%= render "shared/header" %>
  <%= render "shared/toast" %>
    <%= yield %>
    <%= render "shared/footer" %>
</html>

app/views/shared/_footer.html.erb
<div id="footer">
<p>©️2021 YumYum-app, All Rights reserved.</p>
</div>

app/views/shared/_header.html.erb
<div id=header>
 <div class="logo">
  <a href="/">YumYum</a>
 </div>

 <div class="heading">
   <p>◆まずは、メニューを投稿！</p>
   <p>◆気に入ったメニューがあれば、購入してお店を応援！</p>
 </div>

 <div class="link">
   <ul id="nav">
   <%# <% if user_signed_in? %>
    <li>
      <%= link_to "メニュー投稿", new_item_path %>
    </li>
    <li>
       ログイン
    </li>
  <%# <% else %>
    <li>
      新規登録
    </li>
    <li>
      ログアウト
    </li>
    <%# <% end %> 
   </ul>
 </div>
</div>

app/views/shared/_toast.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>